max_width = 120
tab_spaces = 4
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_macro_matchers = true
use_try_shorthand = true
unstable_features = true