name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Build (No Default Features, Release)
      run: cargo build --no-default-features --release
    - name: Build (Default Featurs)
      run: cargo build
